package constants

// Paperdoll константы для слотов экипировки
const (
	PAPERDOLL_UNDER     = 0
	PAPERDOLL_HEAD      = 1
	PAPERDOLL_RHAND     = 2
	PAPERDOLL_LHAND     = 3
	PAPERDOLL_GLOVES    = 4
	PAPERDOLL_CHEST     = 5
	PAPERDOLL_LEGS      = 6
	PAPERDOLL_FEET      = 7
	PAPERDOLL_CLOAK     = 8
	PAPERDOLL_HAIR      = 9
	PAPERDOLL_HAIR2     = 10
	PAPERDOLL_RBRACELET = 11
	PAPERDOLL_LBRACELET = 12
	PAPERDOLL_DECO1     = 13
	PAPERDOLL_DECO2     = 14
	PAPERDOLL_DECO3     = 15
	PAPERDOLL_DECO4     = 16
	PAPERDOLL_DECO5     = 17
	PAPERDOLL_DECO6     = 18
	PAPERDOLL_BELT      = 19
)
